INSERT INTO `cinema`.`films` (`name`,`duration`) VALUES ('Фильм1', 60);
INSERT INTO `cinema`.`films` (`name`,`duration`) VALUES ('Фильм2', 900);
INSERT INTO `cinema`.`films` (`name`,`duration`) VALUES ('Фильм3', 120);
INSERT INTO `cinema`.`films` (`name`,`duration`) VALUES ('Фильм4', 120);
INSERT INTO `cinema`.`films` (`name`,`duration`) VALUES ('Фильм5', 90);
INSERT INTO `cinema`.`sessions` (`film`, `start_dt`, `price`) VALUES (3, '2023-04-13 11:00:00', 300);
INSERT INTO `cinema`.`sessions` (`film`, `start_dt`, `price`) VALUES (1, '2023-04-13 12:00:00', 400);
INSERT INTO `cinema`.`sessions` (`film`, `start_dt`, `price`) VALUES (2, '2023-04-13 13:00:00', 400);
INSERT INTO `cinema`.`sessions` (`film`, `start_dt`, `price`) VALUES (5, '2023-04-13 15:00:00', 600);
INSERT INTO `cinema`.`sessions` (`film`, `start_dt`, `price`) VALUES (3, '2023-04-13 17:00:00', 600);
INSERT INTO `cinema`.`sessions` (`film`, `start_dt`, `price`) VALUES (4, '2023-04-13 21:00:00', 1500);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (1);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (2);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (3);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (4);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (5);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (6);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (1);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (2);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (3);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (4);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (5);
INSERT INTO `cinema`.`tickets` (`session`) VALUES (6);